api_version = "2025-01"

[[extensions]]
name = "Free nap socks"
handle = "free-nap-socks"
type = "function"
description = "Every order includes a free pair of nap socks. Non-negotiable."

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "npm run build"
  path = "dist/function.wasm"
